// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.amount_written", 0);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.7.0");
user_pref("extensions.lastPlatformVersion", "68.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"824c04b4-96a7-4432-816a-89ee381b458f\",\"default-theme@mozilla.org\":\"bb5714f8-7113-4271-bcbb-6c7326599e25\"}");
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "408babdc-00ff-4e96-8c13-3bf188db242");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("security.sandbox.plugin.tempDirSuffix", "71b5dba3-99bd-4f14-9f25-4e18ce17e7aa");
